name: Generate Sponsors README
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Test Locations and List Files
        run: |
          pwd
          ls -a

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: 'README.md'

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: '.'
