name: My README.md settings
on:
  - pull_request
  - push
jobs:
  Setting-up-README-With-GFM:
    - name: Setting up README.md with GFM to enable reaticted HTML tags
    - runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3.0.2
        - uses: micromark/micromark-extension-gfm-tagfilter@main
